designPro/designPro/urls.py
from django.urls import path, include

from django.contrib import admin
from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

designPro/main/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views


app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('accounts/logout', logout_user, name='logout'),
    path('accounts/register', Register.as_view(), name='register'),
    path('accounts/login', auth_views.LoginView.as_view(template_name='main/login.html'), name='login'),
    path('accounts/profile/', ApplicationListView.as_view(), name='profile'),
    path('application/create', create_application, name='application_create'),
    path('application/delete/<int:pk>', application_delete, name='application_delete'),
    path('application/update/<int:pk><str:st>', update_application, name='status_update'),
    path('category', CategoryListView.as_view(), name='category'),
    path('category/create', CategoryCreateView.as_view(), name='category_create'),
    path('category/delete/<int:pk>', category_delete, name='category_delete')
]

designPro/main/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import AbstractUser
from django.utils.crypto import get_random_string
from .utilities import get_timestamp_path


def get_name_file(instance, filename):
    return '/'.join([get_random_string(length=5) + '_' + filename])


def validate_image(field_file_obj):
    filesize = field_file_obj.file.size
    megabyte_limit = 2.0
    if filesize > megabyte_limit * 1024 * 1024:
        raise ValidationError("Максимальный размер файла %sMB" % str(megabyte_limit))


class User(AbstractUser):
    name = models.CharField(max_length=254, verbose_name='Имя', blank=False)
    surname = models.CharField(max_length=254, verbose_name='Фамилия', blank=False)
    patronymic = models.CharField(max_length=254, verbose_name='Отчество', blank=True)
    username = models.CharField(max_length=254, verbose_name='Логин', blank=False, unique=True)
    email = models.CharField(max_length=254, verbose_name='Почта', blank=False, unique=True)
    password = models.CharField(max_length=254, verbose_name='Пароль', blank=False)
    role = models.CharField(max_length=254, verbose_name='Роль',
                            choices=(('admin', 'Администратор'), ('user', 'Пользователь')), default='user')

    USERNAME_FIELD = 'username'

    def __str__(self):
        return str(self.name) + " " + str(self.surname)

    def is_author(self, application):
        if self.pk == application.user.pk:
            return True
        return False

    class Meta(AbstractUser.Meta):
        pass


class Category(models.Model):
    name = models.CharField(max_length=254, verbose_name='Название', blank=False)

    def __str__(self):
        return self.name


class Application(models.Model):
    name = models.CharField(max_length=254, verbose_name='Имя', blank=False)
    description = models.CharField(max_length=500, verbose_name='Описание', blank=False)
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    photo_file = models.ImageField(max_length=254, upload_to=get_timestamp_path, blank=True,
                                   validators=[FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']),
                                               validate_image], help_text='Максимальный размер изображения 2МБ')
    date = models.DateTimeField(verbose_name='Дата добавления', auto_now_add=True, blank=False)

    LOAN_STATUS = (
        ('n', 'Новая'),
        ('p', 'Принято в работу'),
        ('d', 'Выполнено'),
    )

    status = models.CharField(max_length=1, verbose_name='Cтатус',
                              choices=LOAN_STATUS, blank=True, default='n')
    status_comment = models.CharField(max_length=500, verbose_name='Комментарий изменений', blank=True, null=True)
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.name

designPro/main/forms.py
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django import forms
from django.core.validators import RegexValidator

from .models import User, Application, Category


class RegisterUserForm(forms.ModelForm):
    name = forms.CharField(label='Имя', validators=[RegexValidator('^[а-яА-Я- ]+$',
                                                                   message='Разрешены только кириллические '
                                                                           'буквы, дефис и пробелы')],
                           error_messages={'required': 'Обязательное поле'})
    surname = forms.CharField(label='Фамилия', validators=[RegexValidator('^[а-яА-Я- ]+$',
                                                                          message='Разрешены только кириллические '
                                                                                  'буквы, дефис и пробелы')],
                              error_messages={'required': 'Обязательное поле'})
    patronymic = forms.CharField(label='Отчество', required=False, validators=[RegexValidator('^[а-яА-Я- ]+$',
                                                                                              message='Разрешены только кириллические '
                                                                                                      'буквы, дефис и пробелы')])
    username = forms.CharField(label='Логин', validators=[RegexValidator('^[a-zA-Z-]+$',
                                                                         message='Разрешены только латиница и дефис')],
                               error_messages={
                                   'required': 'Обязательное поле',
                                   'unique': 'Данный логин уже занят'
                               })
    email = forms.EmailField(required=True,
                             label='Адрес электронной почты',
                             error_messages={
                                 'invalid': 'Не правильный формат',
                                 'unique': 'Данный почтовый адресс уже занят'
                             })
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput,
                               error_messages={'required': 'Обязательное поле'})
    password2 = forms.CharField(label='Пароль (повторно)',
                                widget=forms.PasswordInput,
                                help_text='Повторите тот же самый пароль еще раз',
                                error_messages={'required': 'Обязательное поле'})

    def clean(self):
        super().clean()
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password and password2 and password != password2:
            raise ValidationError({
                'password2': ValidationError('Пароли не совпадают', code='password_nisnatch')
            })

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ('name', 'surname', 'patronymic', 'username', 'email', 'password', 'password2',)


class AddApplication(forms.ModelForm):
    name = forms.CharField(required=True, label='Название')
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}), label='Описание')
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label='Категория не выбрана',
                                      label='Категория')

    class Meta:
        model = Application
        fields = ('user', 'name', 'description', 'category', 'photo_file')
        widgets = {'user': forms.HiddenInput}


class AddCategory(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class ApplicationUpdateD(forms.ModelForm):
    class Meta:
        model = Application
        fields = ('status', 'photo_file')
        widgets = {'status': forms.HiddenInput}


class ApplicationUpdateP(forms.ModelForm):
    class Meta:
        model = Application
        fields = ('status', 'status_comment')
        widgets = {
            'status': forms.HiddenInput,
        }

designPro/main/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView
from django.contrib.auth import logout

from .filters import ApplicationFilter
from .forms import *

from .models import Application


def index(request):
    in_progress = Application.objects.all().filter(status='p').count()
    done = Application.objects.filter(status='d').order_by('-date')

    context = {
        'in_progress': in_progress,
        'done': done
    }

    return render(request, 'main/index.html', context)


class Register(CreateView):
    model = User
    template_name = 'main/register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:login')


def logout_user(request):
    logout(request)
    return redirect('main:login')


class ApplicationListView(LoginRequiredMixin, ListView):
    model = Application
    template_name = 'main/application_list.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Application.objects.all().order_by('-date')
        else:
            return Application.objects.filter(user=self.request.user).order_by('-date')

    def get_context_data(self, **kwargs):
        context =super().get_context_data(**kwargs)
        context['filter'] = ApplicationFilter(self.request.GET, queryset=self.get_queryset())
        return context


@login_required
def create_application(request):
    if request.method == 'POST':
        form = AddApplication(request.POST, request.FILES)
        if form.is_valid():
            author = form.save(commit=False)
            author.user = request.user
            author.save()
            return redirect('main:profile')
    else:
        form = AddApplication()
    return render(request, 'main/application_form.html', {'form': form})


@login_required
def application_delete(request, pk):
    application = get_object_or_404(Application, pk=pk)
    if not request.user.is_author(application):
        return redirect('main:profile')
    if request.method == 'POST':
        application.delete()
        return redirect('main:profile')
    else:
        context = {'application': application}
        return render(request, 'main/application_delete.html', context)


class CategoryListView(PermissionRequiredMixin, ListView):
    model = Category
    permission_required = 'user.is_superuser'
    template_name = 'main/category_list.html'


class CategoryCreateView(PermissionRequiredMixin, CreateView):
    model = Category
    form_class = AddCategory
    permission_required = 'user.is_superuser'
    success_url = reverse_lazy('main:category')
    template_name = 'main/category_create.html'


def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        return redirect('main:category')
    else:
        context = {'application': category}
        return render(request, 'main/category_delete.html', context)


# def update_application(request, pk):
#   application = get_object_or_404(Application, pk=pk)
#  if request.method == 'POST':
#     form = ApplicationUpdate(request.POST, request.FILES)
#    if form.is_valid():
#       form.save()
#       return redirect('main:profile')
# else:
#   form = AddApplication()
# return render(request, 'main/application_form.html', {'form': form})

@permission_required('user.is_superuser')
def update_application(request, pk, st):
    newapplication = Application.objects.get(id=pk)
    newapplication.save()

    if st == 'd':
        if request.method == 'POST':
            form = ApplicationUpdateD(request.POST, request.FILES)
            if form.is_valid():
                newapplication.photo_file = form.cleaned_data['photo_file']
                newapplication.status = 'd'
                newapplication.save()
                return redirect('main:profile')
        else:
            form = ApplicationUpdateD()
        return render(request, 'main/application_update.html', {'form': form})

    if st == 'p':
        if request.method == 'POST':
            form = ApplicationUpdateP(request.POST, request.FILES)
            if form.is_valid():
                newapplication.status_comment = form.cleaned_data['status_comment']
                newapplication.status = 'p'
                newapplication.save()
                return redirect('main:profile')
        else:
            form = ApplicationUpdateP()
        return render(request, 'main/application_update.html', {'form': form})

designPro/main/templates/main/application_delete.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %} Удаление заявки {% endblock %}
{% block content %}

<div>
    <form method="POST">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить заявку <b>{{ application.name }}</b>?</p>
        {% buttons submit='Удалить' %} {% endbuttons %}
        <a class="btn btn-outline-primary" href="{% url 'main:profile' %}">Нет</a>
    </form>
</div>

{% endblock %}

designPro/main/templates/main/application_form.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %} Добавить заявку {% endblock %}
{% block content %}

<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Добавление заявки</legend>
            {% bootstrap_form form layout='horizontal' %}
        </fieldset>
        <div class="div_buttons">
            {% buttons submit='Добавить' %} {% endbuttons %}
            <a class="btn btn-outline-secondary" href="{% url 'main:profile' %}">Отмена</a>
        </div>
    </form>
</div>
{% endblock content %}

designPro/main/templates/main/application_list.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %} Личный кабинет {% endblock %}
{% block content %}

{% if user.is_superuser %}
<h2>Здравствуйте, {{ user.username }}</h2>
<p>Вы можете перейти на страницу категорий для их управления</p>
<a class="btn btn-outline-success" href="{% url 'main:category' %}">Категории</a>
<br><br><p>А также изменить статусы заявок</p>
{% else %}
<h2>Профиль пользователя {{ user.username }}</h2>
<p>Здравствуйте, {{ user.name }} {{ user.surname }} </p>
<h4>Мои заявки:</h4>
<a class="btn btn-outline-success" href="{% url 'main:application_create' %}">Добавить новую</a>
{% endif %}

<form method="GET" class="filter">
    {% bootstrap_form filter.form layout='horizontal' %}
    <button class="btn btn-success btn-sm" type="submit">Показать</button>
</form>

{% if application_list %}
{% for application in filter.qs %}
<div class="application_card">
    <div class="application_one">
        <div class="application_content">
            <h5 class="application_name">{{ application.name }}</h5>
            <p>{{ application.description }}</p>
            <p>Категория: {{ application.category }}</p>
            <div class="application_info">
                {% if application.status == 'n' %}
                <p>Статус: <br>Новая</p>
                {% elif application.status == 'p' %}
                <p>Статус: <br>Принято в работу</p>
                {% elif application.status == 'd' %}
                <p>Статус: <br>Выполнено</p>
                {% endif %}
                <p>Дата добавления: <br>{{ application.date }}</p>
            </div>
            {% if application.status_comment %}
            <div>
                <p>Комментарий: <br>{{ application.status_comment }}</p>
            </div>
            {% endif %}
        </div>
        {% if application.photo_file %}
        <div class="photo_name_application">
            <img class="photo_file" src="../../media/{{ application.photo_file }}" alt="">
        </div>
        {% endif %}
    </div>
    {% if user.is_superuser and application.status == 'n' %}
    <a class="btn btn-warning btn-sm" href="{% url 'main:status_update' application.pk 'p' %}">Статус - принято в
        работу</a>
    <a class="btn btn-warning btn-sm" href="{% url 'main:status_update' application.pk 'd' %}">Статус - выполнено</a>
    {% elif application.status == 'n' %}
    <a class="btn btn-danger btn-sm" href="{% url 'main:application_delete' application.pk %}">Удалить</a>
    {% endif %}
</div>
{% endfor %}
{% else %}
<p>На данный момент у вас нет заявок, но вы можете их добавить!</p>
{% endif %}
{% endblock %}

designPro/main/templates/main/application_update.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %} Изменение статуса {% endblock %}
{% block content %}

<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Изменение статуса заявки</legend>
            {% bootstrap_form form layout='horizontal' %}
        </fieldset>
        <div class="div_buttons">
            {% buttons submit='Добавить' %} {% endbuttons %}
            <a class="btn btn-outline-secondary" href="{% url 'main:profile' %}">Отмена</a>
        </div>
    </form>
</div>
{% endblock content %}

designPro/main/templates/main/category_create.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %} Добавить заявку {% endblock %}
{% block content %}

<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Добавление Категории</legend>
            {% bootstrap_form form layout='horizontal' %}
        </fieldset>
        <div class="div_buttons">
            {% buttons submit='Добавить' %} {% endbuttons %}
            <a class="btn btn-outline-secondary" href="{% url 'main:category' %}">Отмена</a>
        </div>
    </form>
</div>
{% endblock content %}

designPro/main/templates/main/category_delete.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %} Удаление заявки {% endblock %}
{% block content %}

<div>
    <form method="POST">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить категорию <b>{{ category.name }}</b>?</p>
        {% buttons submit='Да' %} {% endbuttons %}
        <a class="btn btn-outline-primary" href="{% url 'main:profile' %}">Нет</a>
    </form>
</div>

{% endblock %}

designPro/main/templates/main/category_list.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %} Категории {% endblock %}
{% block content %}

<h2>Список доступных категорий</h2>
<p>Вы можете добавлять и удалять категории</p>
<a class="btn btn-outline-success" href="{% url 'main:category_create' %}">Добавить новую</a>
<a class="btn btn-outline-secondary" href="{% url 'main:profile' %}">Назад</a>
{% if category_list %}
{% for category in category_list %}
<div class="application_card">
    <div class="application_content">
        <h5 class="application_name">{{ category.name }}</h5>
    </div>
    <a class="btn btn-danger btn-sm" href="{% url 'main:category_delete' category.pk %}">Удалить</a>
</div>
{% endfor %}
{% endif %}
{% endblock %}

designPro/main/templates/main/index.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %} Главная {% endblock %}
{% block content %}
<p>Количество заявок, принятых в работу на нашем сайте: {{ in_progress }}</p>
<h2>Последние 4 выполненные заявки</h2>
{% for application in done %}
{% if forloop.counter <= 4 %}
<div class="application_card">
    <div class="application_one">
        <div class="application_content">
            <h5 class="application_name">{{ application.name }}</h5>
            <p>Категория: {{ application.category }}</p>
            <div class="application_info">
                <p>Дата добавления: <br>{{ application.date }}</p>
            </div>
        </div>
        {% if application.photo_file %}
        <div class="photo_name_application">
            <img class="photo_file" src="../../media/{{ application.photo_file }}" alt="">
        </div>
        {% endif %}
    </div>
</div>
{% endif %}
{% endfor %}
{% endblock %}

designPro/main/templates/main/login.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %} Вход {% endblock %}
{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="hidden" name="next" value="{{ next }}">
    {% buttons submit='Войти' %} {% endbuttons %}
    <small class="text-muted">
        Нужен аккаунт? <a class="ml-2" href="{% url 'main:register' %}">Регистрация</a>
    </small>
</form>
{% endif %}
{% endblock %}

designPro/main/templates/main/register.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %} Регистрация {% endblock %}
{% block content %}

<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Регистрация</legend>
            {% bootstrap_form form layout='horizontal' %}
        </fieldset>
        {% buttons submit='Зарегистрироваться' %} {% endbuttons %}
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Уже есть аккаунт? <a class="ml-2" href="{% url 'main:login' %}">Вход</a>
        </small>
    </div>
</div>
{% endblock content %}